---
title: "Untitled"
output: html_document
date: "2025-06-23"
---

Code to get specifically just germination genes 

```{r}
library(here)
library(tidyverse)
library(UniprotR)
library(data.table)
library(httr)
library(readr)


###print/check working dir of project
here::here()

### call uniprot API functions to submit jobs and print results

source(here("functions/UniprotFunc.R"))

```

```{r}
Master.Metadata <- read.csv(here("data/output_data/UniprotSporGerm_Master.csv"))

#Germ.Subti <- subset(Master.Metadata, Master.Metadata$subti_func=="germination")
#Germ.Uni <- subset(Master.Metadata, Master.Metadata$UniKey=="germination")

## subset all genes related to germination, either tagged by subti wiki or the uniprot germination keyword, (or both)

Germ.All <- subset(Master.Metadata, Master.Metadata$UniKey=="germination" | Master.Metadata$subti_func=="germination")


## create ID vector list
Germ.vec <- as.data.frame(Germ.All$Entry)
```


```{r}
files = list(
  ids = paste(Germ.vec, collapse = ","),
  from = "UniProtKB_AC-ID",
  to = "UniProtKB")


r <- POST(url = "https://rest.uniprot.org/idmapping/run", body = files, encode = "multipart", accept_json())
submission <- content(r, as = "parsed")


if (isJobReady(submission[["jobId"]])) {
  url <- paste("https://rest.uniprot.org/idmapping/details/", submission[["jobId"]], sep = "")
  r <- GET(url = url, accept_json())
  details <- content(r, as = "parsed")
  url <- getResultsURL(details[["redirectURL"]])
  url <- paste(url, "?compressed=false&format=fasta", sep = "")  # Ensure compression is OFF

  print(url)
  
  r <- GET(url = url, accept_json())
  raw_text <- content(r, as = "text")  # Get raw FASTA text

  fasta.out <- strsplit(raw_text, "\n")[[1]]  # Split into lines
  
  ### Clean headers
  fasta.out <- gsub(">sp\\|", ">", fasta.out)
  fasta.out <- gsub("\\|", " ", fasta.out)

  ### Reformat FASTA: one header, one sequence per entry
  formatted_fasta <- c()
  current_seq <- ""
  
  for (line in fasta.out) {
    if (startsWith(line, ">")) {
      # Store previous sequence if it exists
      if (current_seq != "") {
        formatted_fasta <- c(formatted_fasta, current_seq)
      }
      formatted_fasta <- c(formatted_fasta, line)  # Add new header
      current_seq <- ""  # Reset sequence
    } else {
      current_seq <- paste0(current_seq, line)  # Concatenate sequence
    }
  }
  
  # Add last sequence
  if (current_seq != "") {
    formatted_fasta <- c(formatted_fasta, current_seq)
  }

  ### Write to file
  writeLines(formatted_fasta, here("data/output_data/uniprot_germ.faa"))
}


## for some reason, this results in the first protein in the output being named >tr followed by the normal id info, for now, manual fix of just editing and removing the tr. will troubleshoot later?
```

